---
kind: pipeline
type: docker
name: build

volumes:
  - name: node-modules-cache
    host:
      path: /tmp/drone/cache/node_modules
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: build production image
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    volumes:
      - name: node-modules-cache
        path: /drone/src/node_modules
      - name: docker
        path: /var/run/docker.sock
    settings:
      hosts:
        from_secret: deploy_host
      port:
        from_secret: deploy_port
      user:
        from_secret: deploy_user
      key:
        from_secret: deploy_key
      target:
        from_secret: deploy_target

  - name: deploy
    image: plugins/ansible:3
    settings:
      extra_vars: target=production
      playbook: deploy/deploy.yaml
      galaxy: deploy/requirements.yaml
      inventory: deploy/inventory.yaml
      private_key:
        from_secret: ansible_private_key
      user: deploy

trigger:
  branch:
    - master
  event:
    - push
