version: "3.8"

services:
  app:
    image: node:15.14.0-alpine3.10
    command: sh -c "yarn install && yarn dev -L"
    ports:
      - 4000:4000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql-db
            port: 3306
            user: root
            password: prisma-secret
  mysql:
    image: mysql:5.7
    volumes:
      - green-eggs-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prisma-secret
      MYSQL_DATABASE: green-eggs

volumes:
  green-eggs-mysql-data:
