name: Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

env:
  NODE_VERSION: "14.x" # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: greeneggs-staging
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Resolve Project Dependencies Using Yarn"
        shell: bash
        run: |
          pushd .
          yarn install
          yarn build
          yarn test
          popd

      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "greeneggs" 
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: "Migrate Database"
        shell: bash
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          pushd .
          yarn prisma migrate deploy
          popd
